

embeddings_name: "speechbrain" # ['clova', 'speechbrain', 'xvector']
embeddings_type: "trimmed_2sec"
len_norm: true # true for plda_sph


score_type: 'plda_sph' # ['cos_emb_avg', 'cos_sc_avg', 'plda_sph', 'plda_diag']
by_the_book: true # plda scoring
preprocessing_name: ""
recognizer: 'centroids_online' 
sequential_updates: true

frr_point: 1

calibrate_scores: true
calibration_params_path: ""


threshold_min: 6
threshold_max: 12
thresholds_num: 4

params:
  alpha:
    - null
    - 0.1
