
enrollment_type: "passive"

embeddings_name: "clova" # ['clova', 'speechbrain', 'xvector']
embeddings_type: "2sec"
len_norm: true


score_type: 'plda_sph' # ['cos_emb_avg', 'cos_sc_avg', 'plda_sph', 'plda_diag']
by_the_book: true # plda scoring
preprocessing_name: ""
recognizer: 'memory_unsupervised' 
#sequential_updates: true

frr_point: 1

calibrate_scores: true
calibration_params_path: ""


threshold_min: -10
threshold_max: 20
thresholds_num: 15


params:
    algorithm: 
        - "ahc_plda_sph" 
