
enrollment_type: "passive"

embeddings_name: "speechbrain" # ['clova', 'speechbrain', 'xvector']
embeddings_type: "trimmed_2sec"
len_norm: true


score_type: 'cos_emb_avg' # ['cos_emb_avg', 'cos_sc_avg', 'plda_sph', 'plda_diag']
by_the_book: false # plda scoring
preprocessing_name: ""
recognizer: 'memory_unsupervised' 
#sequential_updates: true

frr_point: 1

calibrate_scores: true
calibration_params_path: ""


threshold_min: -10
threshold_max: 20
thresholds_num: 31

params:
    algorithm: 
        - "ahc" 
