

embeddings_name: "xvector" # ['clova', 'speechbrain', 'xvector']
embeddings_type: "trimmed_2sec"
len_norm: false # false for xvector


score_type: 'plda_diag' # ['cos_emb_avg', 'cos_sc_avg', 'plda_sph', 'plda_diag']
by_the_book: true # plda scoring
plda_len_norm: false
preprocessing_name: "xvector"
recognizer: 'centroids_online' 
sequential_updates: true

frr_point: 1

calibrate_scores: true
calibration_params_path: ""


threshold_min: 7
threshold_max: 7
thresholds_num: 1

params:
  alpha:
    - null
    - 0.1
