

embeddings_name: "xvector" # ['clova', 'speechbrain', 'xvector']
embeddings_type: "trimmed_2sec"
len_norm: false # false for xvector


score_type: 'plda_diag' # ['cos_emb_avg', 'cos_sc_avg', 'plda_sph', 'plda_diag']
by_the_book: false # plda scoring
plda_len_norm: false
preprocessing_name: "xvector"
recognizer: 'centroids_online' 
sequential_updates: true

frr_point: 1

calibrate_scores: true
calibration_params_path: ""


#threshold_min: -2
#threshold_max: 20
#thresholds_num: 23

threshold_min: 3.5
threshold_max: 3.5
thresholds_num: 1

params:
  alpha:
    - null
    - 0.1
  prior_unk:
    - null
    - 0.00001
    - 0.001
    - 0.2
    - 0.5
    - 0.8
    - 0.999
    - 0.99999
